
paths:
  executable: bin/pathtracer

inputs:
  # - assets/dragon.gltf
  # - assets/bust.gltf
  # - assets/single_light.gltf
  # - assets/glass_mirror.gltf
  # - assets/cornell.gltf
  # - assets/two_lights.gltf
  # - assets/many_lights.gltf
  # - assets/Sponza.gltf
  - ../glTF-Sample-Models/2.0/TextureCoordinateTest/glTF/TextureCoordinateTest.gltf

pathtracer:

  logger:
    #define LOG_LEVEL_NONE 0
    #define LOG_LEVEL_ERROR 1
    #define LOG_LEVEL_WARNING 2
    #define LOG_LEVEL_INFO 3
    #define LOG_LEVEL_TRACE 4
    log-level: 4
    log-stdout: True

  output:
    # resolution-x: 2000
    # resolution-y: 2000
    resolution-x: 1024
    resolution-y: 1024

  sampling:
    seed: 42
    samples: 200
    # samples: 400
    samples-every-update: 50

  world:
    # clear-color: 0 0 0
    clear-color: 1 1 1
    # clear-color: 0.509 0.607 0.768
