
paths:
  executable: bin/pathtracer

inputs:
  # - assets/dragon.gltf
  # - assets/bust.gltf
  # - assets/single_light.gltf
  # - assets/glass_mirror.gltf
  # - assets/cornell.gltf
  # - assets/two_lights.gltf
  # - assets/many_lights.gltf
  # - ../glTF-Sample-Models/2.0/TextureCoordinateTest/glTF/TextureCoordinateTest.gltf
  # - ../glTF-Sample-Models/2.0/TextureSettingsTest/glTF/TextureSettingsTest.gltf
  - ../glTF-Sample-Models/2.0/NormalTangentTest/glTF/NormalTangentTest.gltf
  # - ../glTF-Sample-Models/2.0/NormalTangentMirrorTest/glTF/NormalTangentMirrorTest.gltf
  # - ../glTF-Sample-Models/2.0/Sponza/glTF/Sponza.gltf
  # - assets/textured_plane.gltf

pathtracer:

  logger:
    #define LOG_LEVEL_NONE 0
    #define LOG_LEVEL_ERROR 1
    #define LOG_LEVEL_WARNING 2
    #define LOG_LEVEL_INFO 3
    #define LOG_LEVEL_TRACE 4
    log-level: 4
    log-stdout: True

  output:
    # resolution-x: 2000
    # resolution-y: 2000
    resolution-x: 1024
    resolution-y: 1024
    exposure: 2

  sampling:
    seed: 42
    samples: 300
    samples-every-update: 50

  world:
    # clear-color: 0 0 0
    clear-color: 3 3 3
    # clear-color: 0.509 0.607 0.768
    # clear-color-texture: assets/sunny_rose_garden_1k.hdr
    clear-color-texture: assets/farmland_overcast_1k.hdr
    # clear-color-texture: assets/uv_test.png

  default-camera:
    # SPONZA
    # position: 7 1 0
    # target: 0 2 0
    # updir: 0 1 0
    # yfov: 1
    # IF SOMETHIGN IS IN CENTER
    position: 0 0 5
    target: 0 0 0
    updir: 0 1 0
    yfov: 0.8
